image: golang:latest

services:
  - postgres:13-alpine

variables:
  REPO_NAME: gitlab.com/ranfdev/discepto
  POSTGRES_DB: discepto
  POSTGRES_PASSWORD: discepto
  POSTGRES_USER: discepto
  POSTGRES_HOST_AUTH_METHOD: trust

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/

stages:
  - test
  - build
  - staging

format:
  stage: test
  extends: .go-cache
  script:
    - make test

compile:
  stage: build
  extends: .go-cache
  script:
    - make pack
  artifacts:
    paths:
      - ./build/discepto.tar.gz

deploy-to-staging:
  image: alpine
  stage: staging
  environment:
    name: "staging"
  script: |
    apk add openssh-client

    eval $(ssh-agent -s)

    ##
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    ## We're using tr to fix line endings which makes ed25519 keys work
    ## without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    ##
    echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

    sshp="ssh -o StrictHostKeyChecking=no"
    < ./build/discepto.tar.gz $sshp "gitlab@$STAGING_SERVER_DOMAIN" "tar -xzf -"
    $sshp "systemctl --user restart discepto.service" 
